# Generated by Django 5.2.18 on 2026-10-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='RICHARDSON, P.', max_length=120)),
                ('service_date', models.DateField()),
                ('procedure_code', models.CharField(max_length=20)),
                ('procedure_description', models.CharField(max_length=220)),
                ('diagnosis_codes', models.CharField(blank=True, max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Denied', 'Denied'), ('Paid', 'Paid'), ('Rebilled', 'Rebilled')], default='Submitted', max_length=20)),
                ('reference_note', models.CharField(blank=True, max_length=300)),
                ('batch_number', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-service_date', 'procedure_code'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('payer_code', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('member_id', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eob_number', models.CharField(max_length=40, unique=True)),
                ('payer_claim_number', models.CharField(blank=True, max_length=60)),
                ('allowed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_responsibility', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment_code', models.CharField(blank=True, max_length=30)),
                ('denial_reason', models.CharField(blank=True, max_length=300)),
                ('issued_date', models.DateField()),
                ('document_text', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eobs', to='billing.claim')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='billing.insurancepayer'),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='billing.patient'),
        ),
        migrations.CreateModel(
            name='AccountNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('Account Note', 'Account Note'), ('Billing Alert', 'Billing Alert'), ('Follow-up', 'Follow-up'), ('Clinical Alert', 'Clinical Alert')], default='Account Note', max_length=30)),
                ('note', models.TextField()),
                ('created_by', models.CharField(default='Demo Billing User', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='billing.claim')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='billing.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
